spring.application.name=Spring-boot-crud-rest-webservice

spring.datasource.url=jdbc:mysql://localhost:3306/userDB?useSSL=false

spring.datasource.username=root

spring.datasource.password=satya@123

##Hibernate properties
# The SQL dialets makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Hibernate ddl autO(create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
server.port=8082